#!/bin/sh

if [ $# -eq 0 ]
  then
    echo "No arguments supplied. Please use -d for disabling or -e for enabling"
    exit 1
fi

if [ $1 == '-d' ]
   then
     adb shell settings put global window_animation_scale 0
     adb shell settings put global transition_animation_scale 0
     adb shell settings put global animator_duration_scale 0
 elif [ $1 = '-e' ]
     then
      adb shell settings put global window_animation_scale 1
      adb shell settings put global transition_animation_scale 1
      adb shell settings put global animator_duration_scale 1
 else
   echo "No arguments supplied. Please use -d for disabling or -e for enabling"
fi